## CV-RPS REPORT
This is a report done in parellel to the computer vision project using a jupyter notebook in VSCode

# Milestone 1
Goal: Create and download a model from teachable machine. and document the experience.

# Task 1 - Create an image project model with 4 different classes: Rock, Paper, Scissors and Nothing
Creating the model was a little bit of a challenge for something so seemingly simple. I tested different advanced settings in the beginning and ended up with 2 different models that were both having trouble differentiating between the Paper and scissors classes. Finally I settled on a model with fewer images, but that was giving more certain results. This had around 70-120 images per class. I was debaiting having more images and incorperating different hand shapes per class, e.g paper with fingers closed vs spread, but this seemed unnceessarily complicated. As a base model this will be perfect, but I would Like to come back later and create a more refined model  that does include these features

# Task 2 - Download the model
Downloading the model was rather easy, though before finding the video I was unsure which of the tensorflow options to use, Thankfully after looking over the next milestone it would have been easy to realise that keras was the correct option.

# Task 3 - Begin documenting your experiences
Reporting consistently is not one of my strong suits, But this is my attempt. I may come across as too formal or not formal enough at times but It'll do 

# Milestone 2
Goal: create a virtual environment, instrall the dependencies and run the provided code

# Task 1 - Create a new virtual environment:
This task was rather easy though I made the mistake of acting before I had read the task and installed the dependencies before I created the environment. I've never worked with virtual environments in such a way before so I was unsure of what to expect, but it makes basic sense without looking too deep into it for now. It is very helpful for instancing environment to run codde with specific demendencies and allows the prevention of possible clashes or issues with other packages, or allows the use of older packages than are installed or newer packages to test if updating is viable.

# Task 2 - Run the moddel in your local machine.
This task gave me a few issues, These were solved after 2-3 ddays googling. I was mainly having issues with the jupyter notebook failing to start the python kernel. The solution was to uninstall all jupyrter related packages and let VSCode install them automatically after running the code in the notebook. The solution was found here:
https://stackoverflow.com/questions/71003266/kernel-failed-to-start-using-conda-environment-with-jupyter-in-visual-studio-cod

I ran the command line:
python3 -m pip uninstall -y jupyter jupyter_core jupyter-client jupyter-console jupyterlab_pygments notebook qtconsole nbconvert nbformat jupyterlab-widgets nbclient ipykernel ipynb

then reinstalled through VSCode and everything worked fine.

# Task 3 - Get famaliar with the code:
There is alot of the code that I have never seen before and this is my first time working on something more basic than python syntax, so I may need to do a little more learning.
From what I have gathered, the first 5 lienes are just initializing the variables, the while loop is then entered and the camera feed is normalized to fit the dataset. The prediction is then printed to the output in 4 different values corresponding to the classes of the training set: Rock, Paper, Scissors and None. finally the program does this until it is cloeed with the 'q' key, triggering the if statement which leads to a break. or by terminating the program in the IDE. once the while loop is exited via the break the image capture is released and the window is closed.




In [1]:
import cv2 as cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction[[0]])
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-04-25 21:34:22.819755: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/clark/miniconda3/envs/rps-env/lib/python3.8/site-packages/cv2/../../lib64:
2022-04-25 21:34:22.819773: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-04-25 21:34:23.597240: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/clark/miniconda3/envs/rps-env/lib/python3.8/site-packages/cv2/../../lib64:
2022-04-25 21:34:23.597257: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-25 21:34:23.597269: I tensorflow/stream_executor/cuda/cuda_di

Qt: Session management error: Could not open network socket


[[7.2702809e-05 6.7506166e-06 3.3078942e-02 9.6684164e-01]]
[[4.7935609e-05 5.9523027e-06 1.1072159e-02 9.8887396e-01]]
[[3.2233249e-04 6.6677085e-06 2.8724919e-04 9.9938369e-01]]
[[5.8792904e-04 1.7886296e-05 9.7134424e-04 9.9842286e-01]]
[[4.0379839e-04 5.7817921e-05 5.0017396e-05 9.9948835e-01]]
[[1.0032979e-03 1.1365472e-04 5.2151800e-04 9.9836153e-01]]
[[1.6472904e-03 9.6187498e-05 1.5869267e-02 9.8238730e-01]]
[[2.5869785e-03 1.7932708e-04 1.9513847e-01 8.0209523e-01]]
[[5.32261154e-04 1.03309314e-04 1.89138867e-03 9.97473061e-01]]
[[2.0158119e-04 1.5580731e-04 7.5807516e-03 9.9206185e-01]]
[[1.1749489e-04 5.9716222e-05 3.6582001e-03 9.9616456e-01]]
[[5.1487565e-05 8.7455432e-05 2.5924214e-03 9.9726868e-01]]
[[2.2341121e-05 2.6027512e-05 8.1169112e-03 9.9183476e-01]]
[[8.6314521e-06 4.5032225e-06 1.2683366e-04 9.9986005e-01]]
[[1.4593998e-05 1.8246715e-06 3.3754515e-04 9.9964607e-01]]
[[1.7366203e-05 7.9889514e-06 1.7654677e-03 9.9820924e-01]]
[[1.6699951e-05 2.5066820e-05 3.3293

## Milestone 3
Milestone 3 covers the logic necessary for the game of rock paper scissors

# Task 1 - Store the user's and the computer's choices
Having been a while since I used python, This took a few attempts. but through the power of Google and determination I was able to get the inputs, Then after rereading the task I split the code into the 2 different classes

# Rask 2 - Figure out who won
I was almost interested to try and find a way to match two lists to create a smaller if-else chain, using the rock paper scissors of options and adding a paper scissors rock list and matching them. realising that a string was returned from the earlier task I added 

# Task 3 - Create a function to simulatre the game
Simply wrapped my function calls in a function called play() and ran that function after.

# Task 4 - Update the documentation.
This task took an hour or so but was very fun and gave me ideas that I could use to come back at a later date and see how I could do this differently with more knowledge and experience.

## Milestone 4 - Use the Camera to play Rock-Paper-Scissors

# Task 1 - Putting it all together
I started by importing the play function form the manual_rps python file created in Milestone 3.
I then worked on obstracting the value from the modle to get the users choice. This has lead me to needing to create a better keras model as the prediction is not very acurate.
for the next model I will be bringing my hand closer to the camera to allow for less background visibility, this will hopefully lower the effect of light and background variance and allow a more accurate predictive model.

In [3]:
import cv2 as cv2
from keras.models import load_model
import numpy as np
#from manual_rps import play
import time
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
options = ['Rock', 'Paper', 'Scissors','None']

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    max = np.argmax(prediction[0])
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(options[max]) 
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


Paper
None
None
None
Paper
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Paper
Paper
Rock
Rock
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Paper
Pa